package top.hcode.hoj.manager.admin.problem;

import cn.hutool.core.util.IdUtil;
import cn.hutool.json.JSONArray;
import cn.hutool.json.JSONObject;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;
import top.hcode.hoj.judge.self.JudgeDispatcher;
import top.hcode.hoj.pojo.dto.TestJudgeReq;
import top.hcode.hoj.pojo.dto.TestJudgeRes;
import top.hcode.hoj.pojo.entity.problem.Problem;
import top.hcode.hoj.pojo.vo.ProblemAiLanguageProgramVO;
import top.hcode.hoj.utils.Constants;
import top.hcode.hoj.utils.RedisUtils;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Runs the same concrete input/output files through the secondary language
 * implementations generated by AI.  The canonical C++17 program is still
 * judged through the normal verification submission; this runner is only for
 * cross-language compatibility evidence and never changes the official judge
 * record.
 */
@Component
public class ProblemAiMultiLanguageRunner {
    private static final long WAIT_TIMEOUT_MS = 5 * 60 * 1000L;
    private static final long POLL_MS = 300L;

    @Resource private JudgeDispatcher judgeDispatcher;
    @Resource private RedisUtils redisUtils;

    public JSONArray run(Problem problem, List<ProblemAiLanguageProgramVO> programs,
                         List<ProblemAiTestPoint> points) {
        JSONArray languages = new JSONArray();
        if (programs == null) return languages;
        for (ProblemAiLanguageProgramVO program : programs) {
            JSONObject languageResult = new JSONObject()
                    .set("language", program == null ? "未指定" : program.getLanguage());
            JSONArray tests = new JSONArray();
            int passed = 0;
            int concrete = 0;
            if (program == null || StringUtils.isEmpty(program.getCode())) {
                languageResult.set("status", "FAIL").set("passed", 0).set("total", 0)
                        .set("message", "未生成有效源码").set("testPoints", tests);
                languages.add(languageResult);
                continue;
            }
            for (ProblemAiTestPoint point : points) {
                if (!Boolean.TRUE.equals(point.getConcrete())) {
                    tests.add(test(point, "SKIPPED", "动态或样例占位测试点没有独立输入文件"));
                    continue;
                }
                concrete++;
                if (!Boolean.TRUE.equals(point.getInputAvailable())
                        || !Boolean.TRUE.equals(point.getExpectedOutputAvailable())) {
                    tests.add(test(point, "FAIL", "测试点输入或标准输出文件不可读取，未进行多语言判题"));
                    continue;
                }
                try {
                    TestJudgeRes result = runOne(problem, program.getLanguage(), program.getCode(),
                            point.getInput(), point.getExpectedOutput());
                    int status = result == null || result.getStatus() == null
                            ? Constants.Judge.STATUS_SYSTEM_ERROR.getStatus() : result.getStatus();
                    boolean ok = status == Constants.Judge.STATUS_ACCEPTED.getStatus();
                    if (ok) passed++;
                    tests.add(new JSONObject().set("index", point.getIndex())
                            .set("status", ok ? "PASS" : "FAIL")
                            .set("judgeStatus", statusName(status))
                            .set("timeMs", result == null ? 0 : result.getTime())
                            .set("memoryKb", result == null ? 0 : result.getMemory())
                            .set("stderr", emptyAsMarker(result == null ? "" : result.getStderr()))
                            .set("stdout", emptyAsMarker(result == null ? "" : result.getStdout())));
                } catch (Exception e) {
                    tests.add(new JSONObject().set("index", point.getIndex()).set("status", "FAIL")
                            .set("judgeStatus", "SYSTEM_ERROR").set("timeMs", 0).set("memoryKb", 0)
                            .set("stderr", trim(e.getMessage())));
                }
            }
            boolean allPassed = concrete > 0 && passed == concrete;
            languageResult.set("status", allPassed ? "PASS" : "FAIL")
                    .set("passed", passed).set("total", concrete)
                    .set("message", allPassed ? "全部具体测试点通过" : "存在未通过测试点")
                    .set("testPoints", tests);
            languages.add(languageResult);
        }
        return languages;
    }

    private JSONObject test(ProblemAiTestPoint point, String status, String message) {
        return new JSONObject().set("index", point.getIndex()).set("status", status)
                .set("judgeStatus", status).set("timeMs", 0).set("memoryKb", 0)
                .set("stderr", message);
    }

    private TestJudgeRes runOne(Problem problem, String language, String code,
                                String input, String expectedOutput) throws Exception {
        if (StringUtils.isEmpty(language)) throw new IllegalArgumentException("多语言程序缺少语言");
        String key = "AI_MULTILANG_" + IdUtil.simpleUUID();
        TestJudgeReq request = new TestJudgeReq().setUniqueKey(key).setCode(code).setLanguage(language)
                .setTestCaseInput(stripTrailingLineEndings(input))
                .setExpectedOutput(expectedOutput)
                .setTimeLimit(Math.max(1000, problem.getTimeLimit() == null ? 1000 : problem.getTimeLimit()))
                .setMemoryLimit(Math.max(128, problem.getMemoryLimit() == null ? 128 : problem.getMemoryLimit()))
                .setStackLimit(Math.max(128, problem.getStackLimit() == null ? 128 : problem.getStackLimit()))
                .setIsRemoveEndBlank(Boolean.TRUE.equals(problem.getIsRemoveEndBlank()))
                .setProblemJudgeMode(StringUtils.isEmpty(problem.getJudgeMode()) ? "default" : problem.getJudgeMode())
                .setIsFileIO(Boolean.TRUE.equals(problem.getIsFileIO()))
                .setIoReadFileName(problem.getIoReadFileName()).setIoWriteFileName(problem.getIoWriteFileName())
                .setExtraFile(new HashMap<>());
        redisUtils.set(key, TestJudgeRes.builder().status(Constants.Judge.STATUS_PENDING.getStatus()).build(), 10 * 60);
        try {
            judgeDispatcher.sendTestJudgeTask(request);
            long deadline = System.currentTimeMillis() + WAIT_TIMEOUT_MS;
            while (System.currentTimeMillis() < deadline) {
                Object value = redisUtils.get(key);
                if (value instanceof TestJudgeRes) {
                    TestJudgeRes result = (TestJudgeRes) value;
                    if (!Constants.Judge.STATUS_PENDING.getStatus().equals(result.getStatus())) return result;
                }
                TimeUnit.MILLISECONDS.sleep(POLL_MS);
            }
            return TestJudgeRes.builder().status(Constants.Judge.STATUS_SYSTEM_ERROR.getStatus())
                    .stderr("多语言判题超时").build();
        } finally {
            redisUtils.del(key);
        }
    }

    private String statusName(Integer status) {
        for (Constants.Judge item : Constants.Judge.values()) {
            if (item.getStatus().equals(status)) return item.getName();
        }
        return "UNKNOWN(" + status + ")";
    }

    private String stripTrailingLineEndings(String input) {
        if (input == null) return "";
        int end = input.length();
        while (end > 0 && (input.charAt(end - 1) == '\n' || input.charAt(end - 1) == '\r')) end--;
        return input.substring(0, end);
    }

    private String emptyAsMarker(String value) { return StringUtils.isEmpty(value) ? "[stderr/stdout 为空]" : trim(value); }

    private String trim(String value) {
        if (value == null) return "";
        value = value.trim();
        return value.length() > 4000 ? value.substring(0, 4000) : value;
    }
}
